spring.application.name=rlaas-users-service
spring.data.redis.url=${REDIS_URL}
grafana.otlp.cloud.zone=${GRAFANA_CLOUD_ZONE}
grafana.otlp.cloud.instance-id=${GRAFANA_CLOUD_INSTANCE_ID}
grafana.otlp.cloud.api-key=${GRAFANA_CLOUD_API_KEY}